"""add filter table

Revision ID: 8de06ac33ec5
Revises: 0720a4352952
Create Date: 2025-08-27 22:35:52.032050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de06ac33ec5'
down_revision: Union[str, Sequence[str], None] = '0720a4352952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_table('filters')
    # ### end Alembic commands ###
