"""Add user_id to vacancies

Revision ID: c1e8816fc717
Revises: 8de06ac33ec5
Create Date: 2025-09-17 18:05:05.386992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e8816fc717'
down_revision: Union[str, Sequence[str], None] = '8de06ac33ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filters', 'min_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('filters', 'max_salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('filters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('filters_user_id_fkey'), 'filters', type_='foreignkey')
    op.create_foreign_key(None, 'filters', 'users', ['user_id'], ['id'])
    op.add_column('vacancies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('vacancies', 'salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('vacancies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('vacancies_url_key'), 'vacancies', type_='unique')
    op.create_foreign_key(None, 'vacancies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_unique_constraint(op.f('vacancies_url_key'), 'vacancies', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('vacancies', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('vacancies', 'user_id')
    op.drop_constraint(None, 'filters', type_='foreignkey')
    op.create_foreign_key(op.f('filters_user_id_fkey'), 'filters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('filters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('filters', 'max_salary',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('filters', 'min_salary',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
